### PR TITLE
Fix compile error in Jazzy

### PR DESCRIPTION
**Pull request by wentasah**
This fixes the following compile error in Jazzy (since rosbag2 release 0.26.10), which was caused by https://github.com/ros2/rosbag2/pull/2017 and its backport to Jazzy (https://github.com/ros2/rclcpp/pull/2902):

    src/bag2_to_image.cpp:19:10: fatal error: rosbag2_cpp/typesupport_helpers.hpp: No such file or directory
       19 | #include "rosbag2_cpp/typesupport_helpers.hpp"
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Since the same change was not backported to Humble, we need to keep the original code to be compatible with it.

I tested that this change compiles with all supported ROS distros (humble, jazzy, kilted, rolling).

### CODE REVIEW

**Comment by wentasah** [comment]
Reformatted with clang-format.

**Review by wep21 — APPROVED** [review]
rosbag2_cpp version in docker env is still 0.26.9, but changes look good to me.
Thank you for updating api.
```
Found rosbag2_cpp: 0.26.9 (/opt/ros/jazzy/share/rosbag2_cpp/cmake)
```
